//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class AditionalFilePropriety
    {
        [DataMember]
        public int AditionalFileProprietyId { get; set; }
        [DataMember]
        public string ProprietyName { get; set; }
        [DataMember]
        public string ProprietyValue { get; set; }
        [DataMember]
        public int ForeignFileId { get; set; }

        [DataMember]
        public virtual File File { get; set; }
    }


}
